name: 02 - Eventos

on: 
  push:
  pull_request:
  schedule:
    - cron: '21 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: echo "02 - Eventos"